# Состояния для диалога
(GET_URL, GET_SUBTITLE_STYLE, GET_BOTTOM_VIDEO,
 GET_LAYOUT, GET_SUBTITLES_TYPE, GET_CAPITALIZE, CONFIRM_CONFIG, GET_AI_TRANSCRIPTION, GET_SHORTS_NUMBER, GET_TOPUP_METHOD, GET_TOPUP_PACKAGE) = range(11)
