# Состояния для диалога
(GET_URL, GET_SUBTITLE_STYLE, GET_BOTTOM_VIDEO,
 GET_LAYOUT, GET_SUBTITLES_TYPE, CONFIRM_CONFIG, GET_SHORTS_NUMBER, GET_TOPUP_METHOD, GET_TOPUP_PACKAGE, GET_CRYPTO_AMOUNT, GET_BROADCAST_MESSAGE, CRYPTO_PAYMENT, RATING, FEEDBACK, PROCESSING, GET_FEEDBACK_TEXT, GET_TARGETED_BROADCAST_MESSAGE, GET_LANGUAGE) = range(18)
